const  data = [
  
    {
     a:"More people drown in fresh water than in salt water.",
     b:"A penny dropped from the top of the Empire State Building will kill you.",
     c:"Your blood makes up about 8 percent of your body weight.",
     d:"Ancient Greeks and Romans didn't have a number for zero.",
     answer:"b",
     checked: false,
   },
    {
     a:"Squirrels cause most power outages in the U.S.",
     b:"Bamboo grows so fast, it's measured in miles per hour.",
     c:"You can see The Great Wall of China from space.",
     d:"Cruise ships have their own morgues.",
     answer:"c",
     checked: false,
   },
    {
     a:"Cracking your knuckles will give you arthritis.",
     b:"Your brain uses up around 20 percent of your body's blood and oxygen.",
     c:"Giraffes hum to each other at night to make sure their herd stays together.",
     d:"Ladybugs defend themselves by bleeding from their knees.",
     answer:"a",
     checked: false,
   },
   {
     a:"When you sneeze the air blows out of your nose at 160 km/h",
     b:"90% of he world's population lives in northen hemesphere",
     c:"World's longest musical piece lasts 639 years",
     d:"The creator of Rubik's cube never solved it",
     answer:"d",
     checked: false,
   },
   {
     a:"A blue whale's heart is as large as a small car",
     b:"An apple is made up of 50% of air",
     c:"Dolfins often call each other by name",
     d:"Facebook like button was supposed to be awsome button first",
     answer:"b",
     checked: false,
   },
   {
     a:"A volt of lightening has enough energy to toast 100,000 slices of bread",
     b:"Sound travels 4X faster in air than water",
     c:"The world's largest pyramid isn't situated in Egypt",
     d:"The expiration day of a water bottle is not for the water, but for the bottle ",
     answer:"b",
     checked: false,
   },
   {
     a:"Race car drivers sweat so much that they can loose 4.5 kg in one race",
     b:"Your body gives up enough heat in 30 minutes to boil 4 liters of water",
     c:"fish has only memory of three seconds",
     d:"Mount everest isn't the tallest mountain in the world",
     answer:"c",
     checked: false,
   },
   {
     a:"There is a city named boring",
     b:"Art used to be an Olympic sport",
     c:"60% of you brain is made of fat",
     d:"Touching baby birds make their mother bird reject them",
     answer:"d",
     checked: false,
   },
   {
     a:"Stop signs were yellow for thirty years",
     b:"There only 7 varieties of bananas exist in the world",
     c:"The only letter that's not in the periodic table is J",
     d:"You can burn 100 calories per hour just standing and doing nothing",
     answer:"b",
     checked: false,
   },
   {
     a:"Santa clause received a pilot's license",
     b:"There are more cell phones than humans on the planet",
     c:"The bigger brain an animal has the longer it yawns",
     d:"Albert Einstein failed high school math",
     answer:"d",
     checked: false,
   },
   {
     a:"There is 1 in a 1,461 chance for a baby to born on February 29th",
     b:"Fruit stickers are edible",
     c:"An average cloud typically weighs 1000kgs",
     d:"All ants in the world will weigh as much as the whole human population in the world",
     answer:"c",
     checked: false,
   },
   {
     a:"There are more living things inside your body than there are people on earth",
     b:"Domestic chicken is the closest relative of Dinosours",
     c:"There is a town where it rains fish at around same time of the year",
     d:"There is one in a 10,000 chance that a left handed person being killed using a right handed equipment",
     answer:"d",
     checked: false,
   },
   {
     a:"Bacteria make up from 1 to 4 kgs of your body weight",
     b:"There is a room in the Microsoft headquarters that holds a world record for quitest room in the world",
     c:"Can openers were invented before cans were invented",
     d:"Jeep was orginally called G.P",
     answer:"c",
     checked: false,
   },
   {
     a:"Ostrich eggs aren't the largest of all eggs",
     b:"A Jelly fish will melt in the sun",
     c:"All pandas in the world zoos belongs to China",
     d:"The most popular language in the world is not English",
     answer:"a",
     checked: false,
   },
   {
     a:"It never snows on a desert",
     b:"The record for the longest hiccups is for 69 years",
     c:"A Giraffe's tongue is so long that it can clean own ears with it",
     d:"A humming bird's heart beats at an 1,200 beats per minute",
     answer:"a",
     checked: false,
   },
   {
     a:"French was the official language of the England for about 450 years",
     b:"Goats have rectangular pupils",
     c:"If your car could drive upwords you would reach outer space in one day",
     d:"It rains diamond on Jupiter and Saturn",
     answer:"c",
     checked: false,
   },
   {
     a:"High hills were originally men's wear",
     b:"Cotton candy was invented by a dentist",
     c:"Bananas are technically berries",
     d:"Hairs and nails keep growing after death",
     answer:"d",
     checked: false,
   },
   {
     a:"The population of Russia is more than the population of Bangladesh",
     b:"The word muscle comes from the latin word little mouse",
     c:"Owls don't have eye balls",
     d:"Penguins propose to other penguins by giving them a pable",
     answer:"a",
     checked: false,
   },
   {
     a:"Saturn could float in water",
     b:"Salty water boils faster",
     c:"Spider silk are stronger than steel",
     d:"Black holes aren't really black",
     answer:"b",
     checked: false,
   },
   {
     a:"You tongue has it's own unique print like your fingertips",
     b:"Hearing is your fatsest sense",
     c:"Some rainbows can appear in night",
     d:"Bats are blind",
     answer:"d",
     checked: false,
   },
   {
     a:"Carrots used to be yellow once",
     b:"Squirrels plant millions of trees every year",
     c:"Your hair contains gold",
     d:"30% of human DNA is Inhuman",
     answer:"d",
     checked: false,
   },
   {
     a:"One side of your body has more vessels than other",
     b:"There is a 50% less chance to get killed by a Vending machine than to killed by a Shark",
     c:"The first 3D movie was shown in 1922",
     d:"When potatoes are fresh they contain 80% of liquid",
     answer:"b",
     checked: false,
   },
   {
     a:"Astronauts can't cook in space",
     b:"Sharks can have 3,000 teeth at any given time",
     c:"You can't humm while closing your nose",
     d:"Ocean stores 50X more carbon than the atmosphere",
     answer:"a",
     checked: false,
   },
   {
     a:"Corns always have an even number of raws",
     b:"The most expensive cheese on Earth is made up of donkey milk",
     c:"An eighteen inch pizza is more pizza than two 12 inch pizzas",
     d:"You use only 10% of your brain",
     answer:"d",
     checked: false,
   },
   {
     a:"There are more trees on Earth than therer are star in the galaxy",
     b:"A day in Venus is longer than a year in Venus",
     c:"Elephants can jump",
     d:"It is possible to use cooking oil as fuel in flights",
     answer:"c",
     checked: false,
   },
   
   
 
]